name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
    - uses: actions/checkout@v4
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
